apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: smart-hostel
  labels:
    app: mqtt
spec:
  type: ClusterIP
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
  selector:
    app: mqtt
